export type WorkProofTag = "Meta Ads" | "CRM" | "Scale";

export type WorkProofItem = {
  id: string;
  src: string;
  tag: WorkProofTag;
  niche: string;
  metric: string;
  metricLabel: string;
  note: string;
  size: "sm" | "md" | "lg" | "xl";
};

export type WorkProofDetail = WorkProofItem & {
  displayName: string;
  category: string;
  headline: string;
  body: string;
  services: string[];
  market: string;
  expandBg: string;
};

const COLORS = [
  "#FA4D09",
  "#1254EC",
  "#0B1437",
  "#2D1B54",
  "#E8431E",
  "#0F3332",
  "#3A4B62",
  "#0B3BB3",
  "#7C2D12",
  "#134E4A",
  "#4C1D95",
  "#1E3A5F",
  "#9A3412",
  "#0C4A6E",
  "#312E81",
  "#14532D",
  "#831843",
  "#1C1917",
  "#164E63",
  "#3730A3",
] as const;

/** Curated copy for all 59 receipts — verified directly from screenshot dashboards. */
const WORK_PROOF_CURATED: Record<
  string,
  Omit<WorkProofItem, "id" | "src">
> = {
  "wp-001": {
    tag: "Meta Ads",
    niche: "Finance & Wealth",
    metric: "$18.92",
    metricLabel: "CPL · 233 leads",
    note: "49 ad sets scaling finance leads with $13.26 top adset CPL on $4.4K spend.",
    size: "md",
  },
  "wp-002": {
    tag: "Scale",
    niche: "Mortgage Ad Copy",
    metric: "$500 Beat-Rate",
    metricLabel: "guarantee angle",
    note: "Battle-tested ad copies & offer hooks converting cold mortgage traffic.",
    size: "lg",
  },
  "wp-003": {
    tag: "Meta Ads",
    niche: "Lead Gen Campaign",
    metric: "$12.57",
    metricLabel: "CPL · 201 leads",
    note: "201 qualified form leads generated across 3 campaigns on $2,527 spend.",
    size: "sm",
  },
  "wp-004": {
    tag: "Scale",
    niche: "Agency Webinar",
    metric: "1,018",
    metricLabel: "webinar signups",
    note: "$4.50 per registrant across 21 ad sets on $4,582 total spend.",
    size: "xl",
  },
  "wp-005": {
    tag: "Meta Ads",
    niche: "Home Services · FL",
    metric: "280",
    metricLabel: "leads · 15 days",
    note: "$3,196 spent across roofing, gutters, and solar at 2.46% CTR.",
    size: "lg",
  },
  "wp-006": {
    tag: "Meta Ads",
    niche: "Mortgage PPL",
    metric: "$13.63",
    metricLabel: "CPL · 266 leads",
    note: "Wholesale mortgage leads for PPL agency client on $1,785 spend.",
    size: "md",
  },
  "wp-007": {
    tag: "Scale",
    niche: "ClickFunnels Webinar",
    metric: "1,515",
    metricLabel: "opt-ins · 27% rate",
    note: "1,515 webinar registrations at 27.01% opt-in rate on ClickFunnels.",
    size: "md",
  },
  "wp-008": {
    tag: "Scale",
    niche: "Mortgage · Enterprise",
    metric: "10,172",
    metricLabel: "leads · $8.06 CPL",
    note: "$81.9K spent acquiring 10,172 qualified mortgage leads.",
    size: "sm",
  },
  "wp-009": {
    tag: "Meta Ads",
    niche: "Ecom / Info",
    metric: "3.65x",
    metricLabel: "ROAS · $6.8K sales",
    note: "54 purchases in 1 day scaling cold traffic via hobbyist angles.",
    size: "md",
  },
  "wp-010": {
    tag: "Scale",
    niche: "Agency Scale",
    metric: "$4,184",
    metricLabel: "in 1 day · 7.17 ROAS",
    note: "15 purchases at $278.93 AOV in a single 24-hour window on 4 ad sets.",
    size: "lg",
  },
  "wp-011": {
    tag: "Scale",
    niche: "Scale Architecture",
    metric: "$74.8K",
    metricLabel: "in 20 days · 2.96 ROAS",
    note: "754 purchases and $74,865.82 collected across 16 ad sets in 20 days.",
    size: "sm",
  },
  "wp-012": {
    tag: "Scale",
    niche: "Coaching LTO",
    metric: "$1,850",
    metricLabel: "on $2.10 spend · 880x",
    note: "880+ ROAS before breakfast on front-end low ticket offer with $20 daily budget.",
    size: "md",
  },
  "wp-013": {
    tag: "Meta Ads",
    niche: "Paid Webinar",
    metric: "800",
    metricLabel: "paid reg · $4.34 CPL",
    note: "800 paid registrants ($5 upfront ticket) generated on $3,472 spend.",
    size: "xl",
  },
  "wp-014": {
    tag: "Meta Ads",
    niche: "Webinar Funnel",
    metric: "835",
    metricLabel: "leads · $4.57 CPL",
    note: "835 qualified webinar leads on $3,812 total spend (Feb 1 - Mar 18).",
    size: "md",
  },
  "wp-015": {
    tag: "Meta Ads",
    niche: "Webinar Traffic",
    metric: "$1.38",
    metricLabel: "CPC · 2.5K landings",
    note: "2,557 landing page views at $1.38 CPC powering webinar pipeline.",
    size: "lg",
  },
  "wp-016": {
    tag: "Meta Ads",
    niche: "Tracking & CAPI",
    metric: "9.3/10",
    metricLabel: "match quality · CAPI",
    note: "1,360 server events tracked with 9.3/10 event match quality in Events Manager.",
    size: "md",
  },
  "wp-017": {
    tag: "CRM",
    niche: "Ecom Agency CRM",
    metric: "$503K",
    metricLabel: "pipeline · 26 days",
    note: "GHL dashboard pacing $503K opportunity value with $50.5K won in 26 days.",
    size: "sm",
  },
  "wp-018": {
    tag: "CRM",
    niche: "High-Ticket CRM",
    metric: "$165.7K",
    metricLabel: "45 deals · 26 days",
    note: "45 won deals out of 452 opportunities generating $165,760 in 26 days.",
    size: "md",
  },
  "wp-019": {
    tag: "Scale",
    niche: "Low-Ticket Scale",
    metric: "$77.4K",
    metricLabel: "1,650 LTO buyers",
    note: "1,650 low-ticket offer buyers closed in 20 days generating $77,460 (+54.1%).",
    size: "sm",
  },
  "wp-020": {
    tag: "Meta Ads",
    niche: "Wedding Photography",
    metric: "580",
    metricLabel: "leads · $4.79 CPL",
    note: "580 leads generated in 17 days on $2,776 ad spend for luxury photographer.",
    size: "md",
  },
  "wp-021": {
    tag: "CRM",
    niche: "Service CRM",
    metric: "$73.5K",
    metricLabel: "won · 32 days",
    note: "18 won deals totaling $73,500 closed from $595.8K pipeline in 32 days.",
    size: "md",
  },
  "wp-022": {
    tag: "Scale",
    niche: "Funnel Scale",
    metric: "$7,686",
    metricLabel: "daily funnel revenue",
    note: "233 orders with 56% checkout rate, $1,850 upsell, scaling past $7.6K/day.",
    size: "lg",
  },
  "wp-023": {
    tag: "CRM",
    niche: "Roofing · Florida CRM",
    metric: "$111.2K",
    metricLabel: "26 won jobs · 31 days",
    note: "26 closed roofing jobs totaling $111.2K from $511.2K pipeline in 31 days.",
    size: "sm",
  },
  "wp-024": {
    tag: "CRM",
    niche: "Roofing · Texas CRM",
    metric: "$77.1K",
    metricLabel: "19 jobs · 30 days",
    note: "19 closed jobs generating $77.1K won revenue from 164 homeowner leads in Texas.",
    size: "md",
  },
  "wp-025": {
    tag: "Meta Ads",
    niche: "Wealth Management",
    metric: "1,308",
    metricLabel: "OTP leads · $14.67 CPL",
    note: "1,308 phone-verified wealth leads generated on $19,190 spend in 28 days.",
    size: "lg",
  },
  "wp-026": {
    tag: "Scale",
    niche: "B2B SaaS Growth",
    metric: "$71.9K",
    metricLabel: "revenue · 2.78 ROAS",
    note: "748 paying SaaS users acquired generating $71,934 on $25.8K ad spend.",
    size: "xl",
  },
  "wp-027": {
    tag: "Meta Ads",
    niche: "Solar Energy",
    metric: "76",
    metricLabel: "solar leads · 7 days",
    note: "76 qualified homeowner solar appointments at $17.13 CPL on $1.3K spend.",
    size: "sm",
  },
  "wp-028": {
    tag: "Meta Ads",
    niche: "Pressure Washing",
    metric: "167",
    metricLabel: "leads · $13.37 CPL",
    note: "167 qualified commercial & residential leads on $2,232 spend in 30 days.",
    size: "md",
  },
  "wp-029": {
    tag: "Meta Ads",
    niche: "Legal · MVA / PI",
    metric: "76",
    metricLabel: "MVA leads · 5 days",
    note: "76 motor vehicle accident leads delivered in 5 days at $17.13 avg CPL.",
    size: "lg",
  },
  "wp-030": {
    tag: "Meta Ads",
    niche: "Personal Injury",
    metric: "203",
    metricLabel: "PI leads · $18.69 CPL",
    note: "203 qualified personal injury case inquiries on $3,793 total ad spend.",
    size: "sm",
  },
  "wp-031": {
    tag: "Meta Ads",
    niche: "Mortgage · Australia",
    metric: "154",
    metricLabel: "leads · $14.58 CPL",
    note: "154 exclusive Australian mortgage leads generated on $2,245 spend.",
    size: "md",
  },
  "wp-032": {
    tag: "CRM",
    niche: "Chiropractic Clinic",
    metric: "$6,153",
    metricLabel: "44 consults · 3.59 ROAS",
    note: "44 prepaid clinical bookings and $6,153 revenue on $1,714 ad spend in 5 days.",
    size: "sm",
  },
  "wp-033": {
    tag: "Scale",
    niche: "Supplements · DTC",
    metric: "$52.2K",
    metricLabel: "sales · 4.51 ROAS",
    note: "369 ecom orders totaling $52,211.80 generated on $11.5K spend in 17 days.",
    size: "md",
  },
  "wp-034": {
    tag: "Scale",
    niche: "Skool Community",
    metric: "$58.1K",
    metricLabel: "sales · 4.52 ROAS",
    note: "405 member signups across 4 campaigns; single day scaled to $13.5K at 5.95 ROAS.",
    size: "sm",
  },
  "wp-035": {
    tag: "Scale",
    niche: "Ecom & Lead Gen",
    metric: "$134.1K",
    metricLabel: "ecom & lead sales",
    note: "1,073 purchases generating $134.1K + 1,890 leads generated in 9-day run.",
    size: "md",
  },
  "wp-036": {
    tag: "Meta Ads",
    niche: "Legal · Texas PI",
    metric: "530",
    metricLabel: "PI leads · $26.93 CPL",
    note: "530 signed personal injury lead submissions for Texas firm in 7 days.",
    size: "lg",
  },
  "wp-037": {
    tag: "Scale",
    niche: "Ecom DTC Scale",
    metric: "$80.2K",
    metricLabel: "revenue · 3.97 ROAS",
    note: "568 direct-to-consumer orders generated across 10 campaigns in 7 days.",
    size: "md",
  },
  "wp-038": {
    tag: "Scale",
    niche: "Supplements · DTC",
    metric: "$62.1K",
    metricLabel: "in 7 days · 4.50 ROAS",
    note: "427 high-ticket supplement orders at $145 AOV on $13.8K spend in 7 days.",
    size: "sm",
  },
  "wp-039": {
    tag: "Meta Ads",
    niche: "Solar Acquisition",
    metric: "300",
    metricLabel: "leads · $14.71 CPL",
    note: "300 exclusive homeowner solar leads at $14.71 CPL bypassing $90+ CPMs.",
    size: "lg",
  },
  "wp-040": {
    tag: "Scale",
    niche: "AI Voice / Scale",
    metric: "$54.6K",
    metricLabel: "revenue · 3.04 ROAS",
    note: "539 conversions generating $54,635 revenue across 6 ad sets (Apr 1 - 20).",
    size: "md",
  },
  "wp-041": {
    tag: "Scale",
    niche: "Webinar Scaling",
    metric: "680",
    metricLabel: "leads · $5.27 CPL",
    note: "680 high-intent webinar registrations on $3,584 spend in under 3 weeks.",
    size: "lg",
  },
  "wp-042": {
    tag: "CRM",
    niche: "Roofing · Texas CRM",
    metric: "$77.1K",
    metricLabel: "19 jobs · 30 days",
    note: "19 closed jobs generating $77.1K won revenue from 164 homeowner leads in Texas.",
    size: "md",
  },
  "wp-043": {
    tag: "Meta Ads",
    niche: "Wealth Management",
    metric: "1,308",
    metricLabel: "OTP leads · $14.67 CPL",
    note: "1,308 phone-verified wealth leads generated on $19,190 spend in 28 days.",
    size: "xl",
  },
  "wp-044": {
    tag: "Scale",
    niche: "B2B SaaS Growth",
    metric: "$71.9K",
    metricLabel: "revenue · 2.78 ROAS",
    note: "748 paying SaaS users acquired generating $71,934 on $25.8K ad spend.",
    size: "lg",
  },
  "wp-045": {
    tag: "Meta Ads",
    niche: "Solar Energy",
    metric: "76",
    metricLabel: "solar leads · 7 days",
    note: "76 qualified homeowner solar appointments at $17.13 CPL on $1.3K spend.",
    size: "sm",
  },
  "wp-046": {
    tag: "Meta Ads",
    niche: "Pressure Washing",
    metric: "167",
    metricLabel: "leads · $13.37 CPL",
    note: "167 qualified commercial & residential leads on $2,232 spend in 30 days.",
    size: "md",
  },
  "wp-047": {
    tag: "Meta Ads",
    niche: "Legal · MVA / PI",
    metric: "76",
    metricLabel: "MVA leads · 5 days",
    note: "76 motor vehicle accident leads delivered in 5 days at $17.13 avg CPL.",
    size: "md",
  },
  "wp-048": {
    tag: "Meta Ads",
    niche: "Personal Injury",
    metric: "203",
    metricLabel: "PI leads · $18.69 CPL",
    note: "203 qualified personal injury case inquiries on $3,793 total ad spend.",
    size: "lg",
  },
  "wp-049": {
    tag: "Meta Ads",
    niche: "Mortgage · Australia",
    metric: "154",
    metricLabel: "leads · $14.58 CPL",
    note: "154 exclusive Australian mortgage leads generated on $2,245 spend.",
    size: "md",
  },
  "wp-050": {
    tag: "CRM",
    niche: "Chiropractic Clinic",
    metric: "$6,153",
    metricLabel: "44 consults · 3.59 ROAS",
    note: "44 prepaid clinical bookings and $6,153 revenue on $1,714 ad spend in 5 days.",
    size: "md",
  },
  "wp-051": {
    tag: "Scale",
    niche: "Supplements · DTC",
    metric: "$52.2K",
    metricLabel: "sales · 4.51 ROAS",
    note: "369 ecom orders totaling $52,211.80 generated on $11.5K spend in 17 days.",
    size: "md",
  },
  "wp-052": {
    tag: "Scale",
    niche: "Skool Community",
    metric: "$58.1K",
    metricLabel: "sales · 4.52 ROAS",
    note: "405 member signups across 4 campaigns; single day scaled to $13.5K at 5.95 ROAS.",
    size: "lg",
  },
  "wp-053": {
    tag: "Scale",
    niche: "Ecom & Lead Gen",
    metric: "$134.1K",
    metricLabel: "ecom & lead sales",
    note: "1,073 purchases generating $134.1K + 1,890 leads generated in 9-day run.",
    size: "sm",
  },
  "wp-054": {
    tag: "Meta Ads",
    niche: "Legal · Texas PI",
    metric: "530",
    metricLabel: "PI leads · $26.93 CPL",
    note: "530 signed personal injury lead submissions for Texas firm in 7 days.",
    size: "md",
  },
  "wp-055": {
    tag: "Scale",
    niche: "Ecom DTC Scale",
    metric: "$80.2K",
    metricLabel: "revenue · 3.97 ROAS",
    note: "568 direct-to-consumer orders generated across 10 campaigns in 7 days.",
    size: "sm",
  },
  "wp-056": {
    tag: "Scale",
    niche: "Supplements · DTC",
    metric: "$62.1K",
    metricLabel: "in 7 days · 4.50 ROAS",
    note: "427 high-ticket supplement orders at $145 AOV on $13.8K spend in 7 days.",
    size: "xl",
  },
  "wp-057": {
    tag: "Meta Ads",
    niche: "Solar Acquisition",
    metric: "300",
    metricLabel: "leads · $14.71 CPL",
    note: "300 exclusive homeowner solar leads at $14.71 CPL bypassing $90+ CPMs.",
    size: "sm",
  },
  "wp-058": {
    tag: "Scale",
    niche: "AI Voice / Scale",
    metric: "$54.6K",
    metricLabel: "revenue · 3.04 ROAS",
    note: "539 conversions generating $54,635 revenue across 6 ad sets (Apr 1 - 20).",
    size: "lg",
  },
  "wp-059": {
    tag: "Scale",
    niche: "Webinar Scaling",
    metric: "680",
    metricLabel: "leads · $5.27 CPL",
    note: "680 high-intent webinar registrations on $3,584 spend in under 3 weeks.",
    size: "md",
  },
};

const TAG_CYCLE: WorkProofTag[] = ["Meta Ads", "CRM", "Scale"];
const SIZE_CYCLE: WorkProofItem["size"][] = ["sm", "md", "lg", "xl"];

/** All 59 verified screenshot receipts in /public/workprof (wp-001 … wp-059). */
export const WORK_PROOF: WorkProofItem[] = Array.from({ length: 59 }, (_, i) => {
  const n = String(i + 1).padStart(3, "0");
  const id = `wp-${n}`;
  const curated = WORK_PROOF_CURATED[id];
  if (curated) {
    return { id, src: `/workprof/${id}.webp`, ...curated };
  }
  const tag = TAG_CYCLE[i % TAG_CYCLE.length];
  return {
    id,
    src: `/workprof/${id}.webp`,
    tag,
    niche: "Direct Response",
    metric: "Verified",
    metricLabel: "campaign receipt",
    note: "Verified campaign and CRM receipt from live deployment.",
    size: SIZE_CYCLE[i % SIZE_CYCLE.length],
  };
});

type DetailMeta = {
  displayName: string;
  category: string;
  headline: string;
  body: string;
  services: string[];
  market: string;
};

/** Presentation layer — unique niches, stacks, and dashboard copy per receipt. */
const DETAIL_META: Record<string, DetailMeta> = {
  "wp-001": {
    displayName: "Finance Lead Gen",
    category: "Meta Ads · Wealth Acquisition",
    headline: "233 qualified wealth leads on $4,408 spend ($18.92 CPL).",
    body: "49 ad sets scaling high-net-worth investor inquiries, delivering sub-$14 top-performing adset CPL without broker markups.",
    services: ["META ADS", "FINANCE LEAD GEN", "CPL CONTROL", "MULTI-ADSET"],
    market: "UNITED STATES",
  },
  "wp-002": {
    displayName: "Mortgage Copy Architecture",
    category: "Scale · Offer & Copy Angle",
    headline: "High-converting ad copy angles for mortgage acquisition.",
    body: "Multi-temperature ad copy templates engineered to convert cold mortgage borrowers and eliminate low-intent inquiries.",
    services: ["AD COPYWRITING", "OFFER ANGLE", "MORTGAGE ACQUISITION", "MESSAGING"],
    market: "UNITED STATES",
  },
  "wp-003": {
    displayName: "3-Campaign Lead Flow",
    category: "Meta Ads · Form Leads",
    headline: "201 form leads generated at $12.57 CPL ($2.66 top ad set).",
    body: "Multi-campaign lead generation funnel scaling consistent volume across 3 campaigns with top ad sets delivering leads at $2.66 each.",
    services: ["META ADS", "LEAD FORMS", "CAMPAIGN SCALE", "CPL OPTIMIZATION"],
    market: "UNITED STATES",
  },
  "wp-004": {
    displayName: "Agency Webinar Scale",
    category: "Scale · High-Volume Webinar",
    headline: "1,018 webinar registrations in a single month at $4.50 per lead.",
    body: "High-converting B2B webinar registration funnel generating over 1,000 agency-owner signups on $4,582 total media spend.",
    services: ["WEBINAR FUNNEL", "SCALE ARCHITECTURE", "B2B ACQUISITION", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-005": {
    displayName: "Florida Multi-Trade Lead Gen",
    category: "Meta Ads · Hyper-Local Home Services",
    headline: "280 qualified home service leads in 15 days on $3,196 ad spend.",
    body: "High-volume acquisition run across roofing, gutters, and solar in Florida's most competitive markets with 2.46% CTR.",
    services: ["HOME SERVICES", "LOCAL TARGETING", "LEAD FORMS", "META ADS"],
    market: "FLORIDA, USA",
  },
  "wp-006": {
    displayName: "Wholesale Mortgage Engine",
    category: "Meta Ads · Pay-Per-Lead Backend",
    headline: "266 mortgage leads at $13.63 each across refinance & buyer segments.",
    body: "Wholesale lead acquisition infrastructure delivering refinance, investor, and first-time home buyer leads 10x cheaper than reseller markups.",
    services: ["MORTGAGE ADS", "PPL INFRASTRUCTURE", "WHOLESALE LEADS", "LEAD GEN"],
    market: "UNITED STATES",
  },
  "wp-007": {
    displayName: "ClickFunnels Webinar Engine",
    category: "Scale · Webinar Architecture",
    headline: "1,515 webinar opt-ins at 27.01% conversion rate.",
    body: "High-converting ClickFunnels registration page turning 5,610 unique visitors into 1,515 registered attendees.",
    services: ["CLICKFUNNELS", "OPT-IN OPTIMIZATION", "WEBINAR ENGINE", "CONVERSION RATE"],
    market: "UNITED STATES",
  },
  "wp-008": {
    displayName: "Enterprise Mortgage Scale",
    category: "Scale · High-Volume Mortgage",
    headline: "10,172 mortgage leads generated at $8.06 CPL across $81,984 spend.",
    body: "Massive scale deployment bypassing agency broker fees to deliver 10,172 credit-qualified borrower inquiries at wholesale unit economics.",
    services: ["ENTERPRISE ACQUISITION", "MORTGAGE FUNNEL", "SCALE ARCHITECTURE", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-009": {
    displayName: "Hobbyist Niche Acquisition",
    category: "Meta Ads · Cold Traffic Ecom",
    headline: "$6,840 revenue at 3.65x average ROAS (17.43x top adset).",
    body: "Capturing high buyer intent across 7 niche hobbyist ad sets, generating 54 front-end purchases in a single day.",
    services: ["HOBBYIST TARGETING", "COLD TRAFFIC", "ROAS SCALE", "DYNAMIC ADS"],
    market: "UNITED STATES",
  },
  "wp-010": {
    displayName: "Single-Day ROAS Spike",
    category: "Scale · Agency Acquisition",
    headline: "$4,184 revenue in a single day at 7.17 ROAS.",
    body: "Agency scaling client deploying high-converting offer angles across 4 ad sets, achieving 15 purchases at $278.93 AOV and 7.17 ROAS.",
    services: ["AGENCY SCALE", "HIGH ROAS", "OFFER HOOKS", "CONVERSION BOOST"],
    market: "UNITED STATES",
  },
  "wp-011": {
    displayName: "20-Day Revenue Sprint",
    category: "Scale · Revenue Velocity",
    headline: "$74,865 collected in 20 days across 754 purchases.",
    body: "Systematic scaling blueprint across 16 ad sets delivering 754 buyer transactions at $99.29 average order value and 2.96 ROAS.",
    services: ["SCALE ARCHITECTURE", "REVENUE SPRINT", "CHECKOUT FUNNEL", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-012": {
    displayName: "Ultra-High ROAS Low Ticket",
    category: "Scale · Asymmetric Returns",
    headline: "$1,850 cash collected on just $2.10 ad spend (880+ ROAS).",
    body: "Front-end micro-budget campaign capturing rapid buyer checkout and high-ticket order bumps before breakfast for a coaching client.",
    services: ["LOW-TICKET OFFERS", "UPSELL SEQUENCE", "ASYMMETRIC ROAS", "CASH COLLECTION"],
    market: "UNITED STATES",
  },
  "wp-013": {
    displayName: "Paid-Ticket Webinar Funnel",
    category: "Meta Ads · Paid Funnels",
    headline: "800 paid webinar attendees at $4.34 CPL on $27 CPM.",
    body: "Paid front-end ticket model ($5 entry) filtering out freebie seekers and ensuring high show-up rates and buyer readiness for backend offers.",
    services: ["PAID WEBINARS", "META ADS", "TICKET CHECKOUT", "SHOW-UP NURTURE"],
    market: "UNITED STATES",
  },
  "wp-014": {
    displayName: "Webinar Performance Turnaround",
    category: "Meta Ads · Optimization",
    headline: "835 qualified webinar leads at $4.57 CPL across 2 campaigns.",
    body: "Complete overhaul of targeting parameters and video hooks delivering 835 registrants from 2,759 link clicks on $3,812 spend.",
    services: ["WEBINAR OPTIMIZATION", "CPL CONTROL", "AUDIENCE REFINEMENT", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-015": {
    displayName: "Webinar Media Efficiency",
    category: "Meta Ads · Campaign Structure",
    headline: "2,557 landing page visits delivered at $1.38 CPC.",
    body: "Sub-$1.40 cost per link click driving high traffic velocity into high-converting registration pages.",
    services: ["TRAFFIC EFFICIENCY", "CPC OPTIMIZATION", "LANDING PAGES", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-016": {
    displayName: "Conversions API (CAPI) Architecture",
    category: "Meta Ads · Tracking Infrastructure",
    headline: "9.3/10 Meta Event Match Quality via Server CAPI.",
    body: "Server-side Conversions API integration recovering lost iOS tracking signals, deduplicating browser events, and feeding Meta AI clean conversion data.",
    services: ["SERVER-SIDE CAPI", "EVENT MATCHING", "SIGNAL RECOVERY", "TRACKING AUDIT"],
    market: "UNITED STATES",
  },
  "wp-017": {
    displayName: "Agency Pipeline Velocity",
    category: "CRM · Pipeline Health",
    headline: "$503,060 pipeline pacing for eCommerce marketing agency.",
    body: "Real-time CRM dashboard monitoring lead stages, discovery call bookings, and sales rep close rates for a fast-scaling marketing firm.",
    services: ["CRM DASHBOARD", "PIPELINE VELOCITY", "DISCOVERY CALLS", "DEAL TRACKING"],
    market: "UNITED STATES",
  },
  "wp-018": {
    displayName: "High-Ticket Deal Closing",
    category: "CRM · Revenue Growth",
    headline: "$165,760 won across 45 deals in 26 days (+90.91%).",
    body: "High-ticket sales pipeline tracking 45 closed contracts in under a month from $1.61M total opportunity pipeline, delivering 90.9% revenue growth.",
    services: ["HIGH-TICKET CRM", "CLOSE RATE ACCELERATION", "REVENUE ENGINE", "DEAL FLOW"],
    market: "UNITED STATES",
  },
  "wp-019": {
    displayName: "Low-Ticket Offer Scale",
    category: "Scale · Buyer Acquisition",
    headline: "$77,460 in 20 days via 1,650 low-ticket sales (+54.1%).",
    body: "Scaling a front-end low-ticket digital offer to 1,650 new buyers in 20 days, building a massive list of buyers for high-ticket backend conversions.",
    services: ["LOW-TICKET OFFERS", "CUSTOMER ACQUISITION", "UPSELL FUNNEL", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-020": {
    displayName: "Luxury Service Lead Gen",
    category: "Meta Ads · High-Ticket Creative",
    headline: "580 qualified wedding photography leads in 17 days.",
    body: "$2,776 ad spend delivering 580 high-intent inquiries ($4.79 CPL) for a luxury wedding photography studio with instant automated inquiry follow-up.",
    services: ["PORTFOLIO FUNNEL", "META ADS", "LOCAL LUXURY", "AUTOMATED INQUIRY"],
    market: "UNITED STATES",
  },
  "wp-021": {
    displayName: "Service CRM Revenue",
    category: "CRM · Opportunity Tracking",
    headline: "$73,500 won revenue closed from $595.8K pipeline in 32 days.",
    body: "18 closed contracts generating $73.5K in won revenue (+57% vs previous period) across high-intent inbound lead pipelines.",
    services: ["CRM PIPELINE", "WON DEALS", "OPPORTUNITY STAGES", "CLOSE TRACKING"],
    market: "UNITED STATES",
  },
  "wp-022": {
    displayName: "Daily Revenue Scaling",
    category: "Scale · Daily Run Rate",
    headline: "$7,686+ single-day revenue closing in on $10K/day.",
    body: "233 front-end checkout orders with a 56.18% checkout rate and multiple one-time offers powering rapid multi-thousand daily revenue.",
    services: ["SCALE VELOCITY", "DAILY REVENUE", "CHECKOUT ACCELERATION", "OTO FUNNEL"],
    market: "UNITED STATES",
  },
  "wp-023": {
    displayName: "Florida Roofing CRM",
    category: "CRM · Pipeline Overview",
    headline: "$111,200 generated in 31 days (26 won jobs) for Florida roofer.",
    body: "Custom CRM deployment managing 142 opportunities and $511.2K in total pipeline, closing 26 replacement jobs in the first month.",
    services: ["CRM PIPELINE", "ROOFING SYSTEM", "DEAL ATTRIBUTION", "FLORIDA MARKET"],
    market: "FLORIDA, USA",
  },
  "wp-024": {
    displayName: "Texas Roofing Turnkey Funnel",
    category: "CRM · Booked Jobs",
    headline: "$77,100 closed won from 19 booked jobs in 30 days.",
    body: "Direct pipeline integration: Meta ads to roofing funnel to booked estimates, closing 19 roof replacement contracts in Texas.",
    services: ["ROOFING FUNNEL", "APPOINTMENT SYSTEM", "CRM INTEGRATION", "TEXAS MARKET"],
    market: "TEXAS, USA",
  },
  "wp-025": {
    displayName: "Wealth Management OTP Funnel",
    category: "Meta Ads · OTP Verification",
    headline: "1,308 OTP-verified wealth leads at $14.67 CPL in 28 days.",
    body: "$19,190 invested in Meta ads with mandatory SMS OTP mobile verification before submission, delivering 1,308 ultra-high-intent wealth management prospects.",
    services: ["OTP VERIFICATION", "WEALTH MANAGEMENT", "META ADS", "LEAD QUALITY CONTROL"],
    market: "UNITED STATES",
  },
  "wp-026": {
    displayName: "SaaS Acquisition Engine",
    category: "Scale · Enterprise Volume",
    headline: "$71,934 revenue across 748 SaaS purchases at 2.78 ROAS.",
    body: "Direct acquisition funnel scaling 7 campaigns simultaneously, acquiring 748 paying software users on $25.8K total spend.",
    services: ["SAAS ACQUISITION", "ENTERPRISE ADS", "DEMO FUNNEL", "CRM HANDOFF"],
    market: "UNITED STATES",
  },
  "wp-027": {
    displayName: "Rapid Solar Lead Surge",
    category: "Meta Ads · 7-Day Sprint",
    headline: "76 qualified solar leads generated in just 7 days.",
    body: "Hyper-focused 7-day solar campaign generating 76 qualified homeowner leads on $1,301.63 total ad spend ($17.13 average CPL).",
    services: ["SOLAR LEAD GEN", "UTILITY TARGETING", "META ADS", "QUALIFICATION FILTER"],
    market: "UNITED STATES",
  },
  "wp-028": {
    displayName: "Exterior Cleaning Lead Gen",
    category: "Meta Ads · Service Volume",
    headline: "167 qualified pressure washing leads at $13.37 CPL in 30 days.",
    body: "30-day localized Meta campaign across 5 ad sets generating 167 residential and commercial exterior cleaning quote requests on $2,232 spend.",
    services: ["PRESSURE WASHING", "LOCAL ADS", "QUOTE FUNNEL", "CPL EFFICIENCY"],
    market: "UNITED STATES",
  },
  "wp-029": {
    displayName: "Motor Vehicle Accident Intake",
    category: "Meta Ads · Legal Lead Gen",
    headline: "76 motor vehicle accident leads generated in 5 days.",
    body: "High-intent personal injury legal intake funnel capturing accident victims with strict qualification screening before attorney handoff.",
    services: ["LEGAL FUNNEL", "MVA INTAKE", "INJURY SCREENING", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-030": {
    displayName: "Legal Multi-Campaign Scale",
    category: "Meta Ads · Personal Injury",
    headline: "203 qualified personal injury leads across 5 campaigns on $3,793 spend.",
    body: "Multi-campaign legal acquisition architecture maintaining low $18.69 CPL across competitive state jurisdictions.",
    services: ["LEGAL SCALE", "MULTI-CAMPAIGN", "CASE INTAKE", "COMPLIANCE"],
    market: "UNITED STATES",
  },
  "wp-031": {
    displayName: "Australian Mortgage Broker",
    category: "Meta Ads · International",
    headline: "154 Australian mortgage leads on $2,245 spend ($14.58 CPL).",
    body: "Targeted mortgage broker campaign in Australia capturing first-home buyers and refinancing applicants with tailored rate-comparison hooks.",
    services: ["AUSTRALIA CAMPAIGNS", "MORTGAGE BROKER", "RATE COMPARISON", "META ADS"],
    market: "AUSTRALIA",
  },
  "wp-032": {
    displayName: "Prepaid Chiropractic Consults",
    category: "CRM · Prepaid Bookings",
    headline: "44 prepaid patient consults and $6,153 upfront revenue (3.59 ROAS).",
    body: "Eliminated clinic no-shows by collecting upfront consultation fees directly through the online scheduling funnel across 7 targeted campaigns.",
    services: ["PREPAID BOOKINGS", "CLINIC FUNNEL", "LOCAL MEDICAL", "NO-SHOW PREVENTION"],
    market: "UNITED STATES",
  },
  "wp-033": {
    displayName: "DTC Supplement Brand Scale",
    category: "Scale · eCommerce ROAS",
    headline: "$52,211 revenue across 369 orders at 4.51 ROAS.",
    body: "Creative testing engine and high-ticket bundle checkout converting cold social traffic into $52.2K in supplement sales in 17 days.",
    services: ["SUPPLEMENT ECOM", "BUNDLE CHECKOUT", "ROAS OPTIMIZATION", "CREATIVE TESTING"],
    market: "UNITED STATES",
  },
  "wp-034": {
    displayName: "Skool Community Scaling",
    category: "Scale · Community Acquisition",
    headline: "$58,108 revenue across 405 Skool memberships (4.52 ROAS).",
    body: "Direct-response acquisition funnel driving 405 paying members into a Skool community, scaling single-day revenue to $13,554 at 5.95 ROAS.",
    services: ["SKOOL COMMUNITY", "MEMBERSHIP FUNNEL", "LAUNCH SPRINT", "PAID TRAFFIC"],
    market: "GLOBAL",
  },
  "wp-035": {
    displayName: "Cross-Brand Efficiency Desk",
    category: "Scale · Multi-Account",
    headline: "$134,139 in eCommerce sales and 1,890 leads across scaled accounts.",
    body: "Comprehensive media buying desk managing 1,073 ecom purchases ($134.1K) and 1,890 leads ($6.72 CPL) across high-growth accounts.",
    services: ["CROSS-BRAND BUYING", "CPA CONTROL", "MEDIA RULES", "REPORTING COLUMNS"],
    market: "UNITED STATES",
  },
  "wp-036": {
    displayName: "Texas Personal Injury Retainers",
    category: "Meta Ads · High-Value Legal",
    headline: "530 personal injury leads generated on $14,270 spend ($26.93 CPL).",
    body: "Solving legal lead quality issues with strict injury questionnaires, resulting in 530 qualified personal injury case leads for Texas firm in 7 days.",
    services: ["TEXAS LEGAL", "PERSONAL INJURY", "CASE QUALIFICATION", "HIGH-VALUE INTAKE"],
    market: "TEXAS, USA",
  },
  "wp-037": {
    displayName: "Horizontal eCommerce Scale",
    category: "Scale · Multi-Adset",
    headline: "$80,227 revenue across 568 orders and 10 campaigns (3.97 ROAS).",
    body: "Horizontal campaign architecture distributing ad spend across 10 scaled campaigns to prevent creative fatigue and maintain 3.97 ROAS.",
    services: ["HORIZONTAL SCALE", "ECOM ADS", "FATIGUE PREVENTION", "PROFIT MARGINS"],
    market: "UNITED STATES",
  },
  "wp-038": {
    displayName: "7-Day Supplement Revenue Surge",
    category: "Scale · DTC Power Sprint",
    headline: "$62,182 in 7 days at 4.50 ROAS ($145 AOV).",
    body: "High-ticket supplement brand scale run generating over $62K in 7 days with a $145 average order value across 5 campaigns.",
    services: ["HIGH-TICKET ECOM", "SUPPLEMENT SCALE", "AOV EXPANSION", "ROAS SCALE"],
    market: "UNITED STATES",
  },
  "wp-039": {
    displayName: "Direct Solar Lead Engine",
    category: "Meta Ads · Disruptive Cost",
    headline: "300 exclusive solar leads at $14.71 CPL beating $90+ CPM brokers.",
    body: "Bypassing overpriced broker networks with direct homeowner ads, delivering 300 exclusive solar inquiries with zero shared-lead competition.",
    services: ["SOLAR FUNNELS", "DIRECT-TO-HOMEOWNER", "CPL CONTROL", "META CAMPAIGNS"],
    market: "UNITED STATES",
  },
  "wp-040": {
    displayName: "AI Agent Scaling Funnel",
    category: "Scale · AI Software",
    headline: "$54,635 revenue across 539 purchases and 237 registrations.",
    body: "High-converting acquisition funnel for AI voice software, generating $54.6K in customer revenue at 3.04 ROAS in 20 days.",
    services: ["AI VOICE AGENTS", "SOFTWARE SCALE", "REVENUE ENGINE", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-041": {
    displayName: "3-Week Webinar Scale",
    category: "Scale · Rapid Scaling",
    headline: "680 webinar registrations in under 3 weeks at $5.27 CPL.",
    body: "3-week sprint scaling webinar ad spend across 3 campaigns, generating 680 qualified attendees with top ad sets at $3.78 per lead.",
    services: ["RAPID SCALING", "WEBINAR FUNNEL", "CPL OPTIMIZATION", "AUDIENCE SCALE"],
    market: "UNITED STATES",
  },
  "wp-042": {
    displayName: "Texas Roofing Turnkey Funnel",
    category: "CRM · Booked Jobs",
    headline: "$77,100 closed won from 19 booked jobs in 30 days.",
    body: "Direct pipeline integration: Meta ads to roofing funnel to booked estimates, closing 19 roof replacement contracts in Texas.",
    services: ["ROOFING FUNNEL", "APPOINTMENT SYSTEM", "CRM INTEGRATION", "TEXAS MARKET"],
    market: "TEXAS, USA",
  },
  "wp-043": {
    displayName: "Wealth Management OTP Funnel",
    category: "Meta Ads · OTP Verification",
    headline: "1,308 OTP-verified wealth leads at $14.67 CPL in 28 days.",
    body: "$19,190 invested in Meta ads with mandatory SMS OTP mobile verification before submission, delivering 1,308 ultra-high-intent wealth management prospects.",
    services: ["OTP VERIFICATION", "WEALTH MANAGEMENT", "META ADS", "LEAD QUALITY CONTROL"],
    market: "UNITED STATES",
  },
  "wp-044": {
    displayName: "SaaS Acquisition Engine",
    category: "Scale · Enterprise Volume",
    headline: "$71,934 revenue across 748 SaaS purchases at 2.78 ROAS.",
    body: "Direct acquisition funnel scaling 7 campaigns simultaneously, acquiring 748 paying software users on $25.8K total spend.",
    services: ["SAAS ACQUISITION", "ENTERPRISE ADS", "DEMO FUNNEL", "CRM HANDOFF"],
    market: "UNITED STATES",
  },
  "wp-045": {
    displayName: "Rapid Solar Lead Surge",
    category: "Meta Ads · 7-Day Sprint",
    headline: "76 qualified solar leads generated in just 7 days.",
    body: "Hyper-focused 7-day solar campaign generating 76 qualified homeowner leads on $1,301.63 total ad spend ($17.13 average CPL).",
    services: ["SOLAR LEAD GEN", "UTILITY TARGETING", "META ADS", "QUALIFICATION FILTER"],
    market: "UNITED STATES",
  },
  "wp-046": {
    displayName: "Exterior Cleaning Lead Gen",
    category: "Meta Ads · Service Volume",
    headline: "167 qualified pressure washing leads at $13.37 CPL in 30 days.",
    body: "30-day localized Meta campaign across 5 ad sets generating 167 residential and commercial exterior cleaning quote requests on $2,232 spend.",
    services: ["PRESSURE WASHING", "LOCAL ADS", "QUOTE FUNNEL", "CPL EFFICIENCY"],
    market: "UNITED STATES",
  },
  "wp-047": {
    displayName: "Motor Vehicle Accident Intake",
    category: "Meta Ads · Legal Lead Gen",
    headline: "76 motor vehicle accident leads generated in 5 days.",
    body: "High-intent personal injury legal intake funnel capturing accident victims with strict qualification screening before attorney handoff.",
    services: ["LEGAL FUNNEL", "MVA INTAKE", "INJURY SCREENING", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-048": {
    displayName: "Legal Multi-Campaign Scale",
    category: "Meta Ads · Personal Injury",
    headline: "203 qualified personal injury leads across 5 campaigns on $3,793 spend.",
    body: "Multi-campaign legal acquisition architecture maintaining low $18.69 CPL across competitive state jurisdictions.",
    services: ["LEGAL SCALE", "MULTI-CAMPAIGN", "CASE INTAKE", "COMPLIANCE"],
    market: "UNITED STATES",
  },
  "wp-049": {
    displayName: "Australian Mortgage Broker",
    category: "Meta Ads · International",
    headline: "154 Australian mortgage leads on $2,245 spend ($14.58 CPL).",
    body: "Targeted mortgage broker campaign in Australia capturing first-home buyers and refinancing applicants with tailored rate-comparison hooks.",
    services: ["AUSTRALIA CAMPAIGNS", "MORTGAGE BROKER", "RATE COMPARISON", "META ADS"],
    market: "AUSTRALIA",
  },
  "wp-050": {
    displayName: "Prepaid Chiropractic Consults",
    category: "CRM · Prepaid Bookings",
    headline: "44 prepaid patient consults and $6,153 upfront revenue (3.59 ROAS).",
    body: "Eliminated clinic no-shows by collecting upfront consultation fees directly through the online scheduling funnel across 7 targeted campaigns.",
    services: ["PREPAID BOOKINGS", "CLINIC FUNNEL", "LOCAL MEDICAL", "NO-SHOW PREVENTION"],
    market: "UNITED STATES",
  },
  "wp-051": {
    displayName: "DTC Supplement Brand Scale",
    category: "Scale · eCommerce ROAS",
    headline: "$52,211 revenue across 369 orders at 4.51 ROAS.",
    body: "Creative testing engine and high-ticket bundle checkout converting cold social traffic into $52.2K in supplement sales in 17 days.",
    services: ["SUPPLEMENT ECOM", "BUNDLE CHECKOUT", "ROAS OPTIMIZATION", "CREATIVE TESTING"],
    market: "UNITED STATES",
  },
  "wp-052": {
    displayName: "Skool Community Scaling",
    category: "Scale · Community Acquisition",
    headline: "$58,108 revenue across 405 Skool memberships (4.52 ROAS).",
    body: "Direct-response acquisition funnel driving 405 paying members into a Skool community, scaling single-day revenue to $13,554 at 5.95 ROAS.",
    services: ["SKOOL COMMUNITY", "MEMBERSHIP FUNNEL", "LAUNCH SPRINT", "PAID TRAFFIC"],
    market: "GLOBAL",
  },
  "wp-053": {
    displayName: "Cross-Brand Efficiency Desk",
    category: "Scale · Multi-Account",
    headline: "$134,139 in eCommerce sales and 1,890 leads across scaled accounts.",
    body: "Comprehensive media buying desk managing 1,073 ecom purchases ($134.1K) and 1,890 leads ($6.72 CPL) across high-growth accounts.",
    services: ["CROSS-BRAND BUYING", "CPA CONTROL", "MEDIA RULES", "REPORTING COLUMNS"],
    market: "UNITED STATES",
  },
  "wp-054": {
    displayName: "Texas Personal Injury Retainers",
    category: "Meta Ads · High-Value Legal",
    headline: "530 personal injury leads generated on $14,270 spend ($26.93 CPL).",
    body: "Solving legal lead quality issues with strict injury questionnaires, resulting in 530 qualified personal injury case leads for Texas firm in 7 days.",
    services: ["TEXAS LEGAL", "PERSONAL INJURY", "CASE QUALIFICATION", "HIGH-VALUE INTAKE"],
    market: "TEXAS, USA",
  },
  "wp-055": {
    displayName: "Horizontal eCommerce Scale",
    category: "Scale · Multi-Adset",
    headline: "$80,227 revenue across 568 orders and 10 campaigns (3.97 ROAS).",
    body: "Horizontal campaign architecture distributing ad spend across 10 scaled campaigns to prevent creative fatigue and maintain 3.97 ROAS.",
    services: ["HORIZONTAL SCALE", "ECOM ADS", "FATIGUE PREVENTION", "PROFIT MARGINS"],
    market: "UNITED STATES",
  },
  "wp-056": {
    displayName: "7-Day Supplement Revenue Surge",
    category: "Scale · DTC Power Sprint",
    headline: "$62,182 in 7 days at 4.50 ROAS ($145 AOV).",
    body: "High-ticket supplement brand scale run generating over $62K in 7 days with a $145 average order value across 5 campaigns.",
    services: ["HIGH-TICKET ECOM", "SUPPLEMENT SCALE", "AOV EXPANSION", "ROAS SCALE"],
    market: "UNITED STATES",
  },
  "wp-057": {
    displayName: "Direct Solar Lead Engine",
    category: "Meta Ads · Disruptive Cost",
    headline: "300 exclusive solar leads at $14.71 CPL beating $90+ CPM brokers.",
    body: "Bypassing overpriced broker networks with direct homeowner ads, delivering 300 exclusive solar inquiries with zero shared-lead competition.",
    services: ["SOLAR FUNNELS", "DIRECT-TO-HOMEOWNER", "CPL CONTROL", "META CAMPAIGNS"],
    market: "UNITED STATES",
  },
  "wp-058": {
    displayName: "AI Agent Scaling Funnel",
    category: "Scale · AI Software",
    headline: "$54,635 revenue across 539 purchases and 237 registrations.",
    body: "High-converting acquisition funnel for AI voice software, generating $54.6K in customer revenue at 3.04 ROAS in 20 days.",
    services: ["AI VOICE AGENTS", "SOFTWARE SCALE", "REVENUE ENGINE", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-059": {
    displayName: "3-Week Webinar Scale",
    category: "Scale · Rapid Scaling",
    headline: "680 webinar registrations in under 3 weeks at $5.27 CPL.",
    body: "3-week sprint scaling webinar ad spend across 3 campaigns, generating 680 qualified attendees with top ad sets at $3.78 per lead.",
    services: ["RAPID SCALING", "WEBINAR FUNNEL", "CPL OPTIMIZATION", "AUDIENCE SCALE"],
    market: "UNITED STATES",
  },
};

function peerReceipts(item: WorkProofItem, count = 2): string[] {
  const peers = WORK_PROOF.filter(
    (p) => p.tag === item.tag && p.id !== item.id
  ).slice(0, count);
  return [item.src, ...peers.map((p) => p.src)];
}

export const WORK_PROOF_DETAILED: WorkProofDetail[] = WORK_PROOF.map(
  (item, i) => {
    const meta = DETAIL_META[item.id] ?? {
      displayName: item.niche,
      category: `${item.tag} · Proof`,
      headline: `${item.metric} — ${item.metricLabel}.`,
      body: item.note,
      services: [item.tag.toUpperCase(), "FUNNEL", "TRACKING"],
      market: "UNITED STATES",
    };
    return {
      ...item,
      ...meta,
      expandBg: COLORS[i % COLORS.length],
    };
  }
);

/** Homepage featured subset (six distinct niches + colors). */
export const WORK_PROOF_FEATURED_IDS = [
  "wp-010",
  "wp-011",
  "wp-012",
  "wp-018",
  "wp-034",
  "wp-038",
] as const;

export function getWorkProofFeatured(): WorkProofDetail[] {
  return WORK_PROOF_FEATURED_IDS.map(
    (id) => WORK_PROOF_DETAILED.find((p) => p.id === id)!
  ).filter(Boolean);
}

export function getWorkProofReceipts(item: WorkProofDetail | WorkProofItem): string[] {
  return peerReceipts(item);
}

export const WORK_PROOF_FILTERS = [
  "All",
  "Meta Ads",
  "CRM",
  "Scale",
] as const;
