export type WorkProofItem = {
  id: string;
  src: string;
  tag: "Meta Ads" | "CRM" | "Scale";
  niche: string;
  metric: string;
  metricLabel: string;
  note: string;
  size: "sm" | "md" | "lg" | "xl";
};

/** Curated receipts from /public/workproof — real Meta + CRM dashboards. */
export const WORK_PROOF: WorkProofItem[] = [
  {
    id: "wp-001",
    src: "/workproof/wp-001.png",
    tag: "Meta Ads",
    niche: "Roofing",
    metric: "$3.75",
    metricLabel: "cost per lead",
    note: "25 form leads in a day — $93 spent.",
    size: "md",
  },
  {
    id: "wp-006",
    src: "/workproof/wp-006.png",
    tag: "Meta Ads",
    niche: "Roofing",
    metric: "$14.58",
    metricLabel: "CPL · 154 leads",
    note: "While owners were still paying $80+ elsewhere.",
    size: "lg",
  },
  {
    id: "wp-016",
    src: "/workproof/wp-016.png",
    tag: "CRM",
    niche: "Roofing · TX",
    metric: "$77K",
    metricLabel: "closed · 30 days",
    note: "Meta ads → roofing funnel → booked jobs.",
    size: "xl",
  },
  {
    id: "wp-026",
    src: "/workproof/wp-026.png",
    tag: "Scale",
    niche: "Mortgage",
    metric: "10,172",
    metricLabel: "leads · $8.06 CPL",
    note: "$82K spent. Same leads agencies resell for $80–$100.",
    size: "xl",
  },
  {
    id: "wp-041",
    src: "/workproof/wp-041.png",
    tag: "CRM",
    niche: "Roofing · FL",
    metric: "$111K",
    metricLabel: "won · 31 days",
    note: "Built from the ground up — 26 won opportunities.",
    size: "lg",
  },
  {
    id: "wp-003",
    src: "/workproof/wp-003.png",
    tag: "Meta Ads",
    niche: "Lead Gen",
    metric: "Live",
    metricLabel: "ads manager",
    note: "Campaign-level cost & result cut.",
    size: "sm",
  },
  {
    id: "wp-008",
    src: "/workproof/wp-008.png",
    tag: "Meta Ads",
    niche: "Service",
    metric: "CPL",
    metricLabel: "proof cut",
    note: "Million Dollar Media™ column view.",
    size: "md",
  },
  {
    id: "wp-012",
    src: "/workproof/wp-012.png",
    tag: "Meta Ads",
    niche: "Roofing",
    metric: "Daily",
    metricLabel: "spend control",
    note: "Tight budgets. Measurable leads.",
    size: "sm",
  },
  {
    id: "wp-018",
    src: "/workproof/wp-018.png",
    tag: "CRM",
    niche: "Pipeline",
    metric: "Won",
    metricLabel: "revenue view",
    note: "Dashboard receipts — not screenshots of vibes.",
    size: "md",
  },
  {
    id: "wp-022",
    src: "/workproof/wp-022.png",
    tag: "Meta Ads",
    niche: "Volume",
    metric: "Ads",
    metricLabel: "manager cut",
    note: "Multi-campaign visibility.",
    size: "sm",
  },
  {
    id: "wp-028",
    src: "/workproof/wp-028.png",
    tag: "Scale",
    niche: "Lead Gen",
    metric: "High",
    metricLabel: "volume run",
    note: "When the machine is warmed up.",
    size: "md",
  },
  {
    id: "wp-032",
    src: "/workproof/wp-032.png",
    tag: "Meta Ads",
    niche: "Service",
    metric: "CPL",
    metricLabel: "efficiency",
    note: "Cost per result, not vanity reach.",
    size: "sm",
  },
  {
    id: "wp-035",
    src: "/workproof/wp-035.png",
    tag: "CRM",
    niche: "Ops",
    metric: "Pipeline",
    metricLabel: "status",
    note: "Open vs won — in the clear.",
    size: "md",
  },
  {
    id: "wp-038",
    src: "/workproof/wp-038.png",
    tag: "Meta Ads",
    niche: "Lead Gen",
    metric: "Spend",
    metricLabel: "vs results",
    note: "Where every dollar went.",
    size: "sm",
  },
  {
    id: "wp-042",
    src: "/workproof/wp-042.png",
    tag: "CRM",
    niche: "Roofing",
    metric: "Closed",
    metricLabel: "jobs",
    note: "Revenue that hit the bank.",
    size: "lg",
  },
  {
    id: "wp-045",
    src: "/workproof/wp-045.png",
    tag: "Meta Ads",
    niche: "Service",
    metric: "Form",
    metricLabel: "leads",
    note: "Qualified inbound at scale.",
    size: "sm",
  },
  {
    id: "wp-048",
    src: "/workproof/wp-048.png",
    tag: "Scale",
    niche: "Multi",
    metric: "Multi",
    metricLabel: "campaign",
    note: "Stacked accounts. Same system.",
    size: "md",
  },
  {
    id: "wp-052",
    src: "/workproof/wp-052.png",
    tag: "CRM",
    niche: "Funnel",
    metric: "Conv.",
    metricLabel: "rate view",
    note: "From click to calendar.",
    size: "sm",
  },
  {
    id: "wp-055",
    src: "/workproof/wp-055.png",
    tag: "Meta Ads",
    niche: "Lead Gen",
    metric: "CTR",
    metricLabel: "efficiency",
    note: "Creative that earns its spend.",
    size: "md",
  },
  {
    id: "wp-058",
    src: "/workproof/wp-058.png",
    tag: "CRM",
    niche: "Revenue",
    metric: "Won",
    metricLabel: "opportunities",
    note: "The only scoreboard that matters.",
    size: "lg",
  },
];

export const WORK_PROOF_FILTERS = [
  "All",
  "Meta Ads",
  "CRM",
  "Scale",
] as const;
