export type WorkProofTag = "Meta Ads" | "CRM" | "Scale";

export type WorkProofItem = {
  id: string;
  src: string;
  tag: WorkProofTag;
  niche: string;
  metric: string;
  metricLabel: string;
  note: string;
  size: "sm" | "md" | "lg" | "xl";
};

export type WorkProofDetail = WorkProofItem & {
  displayName: string;
  category: string;
  headline: string;
  body: string;
  services: string[];
  market: string;
  expandBg: string;
};

const COLORS = [
  "#FA4D09",
  "#1254EC",
  "#0B1437",
  "#2D1B54",
  "#E8431E",
  "#0F3332",
  "#3A4B62",
  "#0B3BB3",
  "#7C2D12",
  "#134E4A",
  "#4C1D95",
  "#1E3A5F",
  "#9A3412",
  "#0C4A6E",
  "#312E81",
  "#14532D",
  "#831843",
  "#1C1917",
  "#164E63",
  "#3730A3",
] as const;

/** Curated copy for all 59 receipts — verified directly from screenshot dashboards. */
const WORK_PROOF_CURATED: Record<
  string,
  Omit<WorkProofItem, "id" | "src">
> = {
  "wp-001": {
    tag: "Meta Ads",
    niche: "Roofing",
    metric: "$3.75",
    metricLabel: "cost per lead",
    note: "25 form leads in a day — $93 spent.",
    size: "md",
  },
  "wp-002": {
    tag: "CRM",
    niche: "Roofing Agency",
    metric: "$134.1K",
    metricLabel: "revenue closed",
    note: "Full pipeline attribution for roofing marketing agency.",
    size: "lg",
  },
  "wp-003": {
    tag: "Meta Ads",
    niche: "Roofing Lead Gen",
    metric: "$14.80",
    metricLabel: "avg lead cost",
    note: "Qualified exclusive roofing leads with zip-code filters.",
    size: "sm",
  },
  "wp-004": {
    tag: "Scale",
    niche: "Home Services · FL",
    metric: "280",
    metricLabel: "leads · 15 days",
    note: "$3,196 spent across roofing, gutters, and solar.",
    size: "xl",
  },
  "wp-005": {
    tag: "CRM",
    niche: "Roofing Agency",
    metric: "$546K",
    metricLabel: "in 67 days",
    note: "152 closed deals from 975 conversations.",
    size: "lg",
  },
  "wp-006": {
    tag: "Meta Ads",
    niche: "Roofing & Solar",
    metric: "$14.58",
    metricLabel: "CPL · 154 leads",
    note: "While owners were still paying $80+ elsewhere.",
    size: "md",
  },
  "wp-007": {
    tag: "Scale",
    niche: "Roofing Funnel",
    metric: "$98.4K",
    metricLabel: "20-day pipeline",
    note: "Full Meta ads to calendar funnel system.",
    size: "md",
  },
  "wp-008": {
    tag: "Meta Ads",
    niche: "Roofing Ads",
    metric: "$16.20",
    metricLabel: "verified CPL",
    note: "Quality-gated forms filtering tire-kickers on Meta.",
    size: "sm",
  },
  "wp-009": {
    tag: "Meta Ads",
    niche: "Roofing Attribution",
    metric: "4.2x",
    metricLabel: "pipeline ROAS",
    note: "Deep CRM attribution from click to closed job.",
    size: "md",
  },
  "wp-010": {
    tag: "Scale",
    niche: "Roofing · Dallas TX",
    metric: "$127.5K",
    metricLabel: "pipeline in TX",
    note: "Targeted Dallas commercial & residential roofing ads.",
    size: "lg",
  },
  "wp-011": {
    tag: "Meta Ads",
    niche: "Roofing Campaigns",
    metric: "$17.40",
    metricLabel: "cost per booked call",
    note: "High-intent homeowner targeting on Meta.",
    size: "sm",
  },
  "wp-012": {
    tag: "Meta Ads",
    niche: "Roofing Lead Control",
    metric: "88 Leads",
    metricLabel: "at $12.10 CPL",
    note: "Strict daily spend caps with high qualification.",
    size: "md",
  },
  "wp-013": {
    tag: "Scale",
    niche: "Roofing Systems",
    metric: "$340K",
    metricLabel: "4-month scale",
    note: "Compounding returns across 4 consecutive months.",
    size: "xl",
  },
  "wp-014": {
    tag: "Meta Ads",
    niche: "Roofing Campaigns",
    metric: "295",
    metricLabel: "leads · $6.6K spend",
    note: "$22.58 CPL for verified replacement jobs.",
    size: "md",
  },
  "wp-015": {
    tag: "CRM",
    niche: "Roofing · FL",
    metric: "$111K",
    metricLabel: "in 31 days",
    note: "Built from the ground up: 26 closed jobs.",
    size: "lg",
  },
  "wp-016": {
    tag: "CRM",
    niche: "Roofing · Texas",
    metric: "$77K",
    metricLabel: "closed in 30 days",
    note: "Meta ads → Roofing funnel → Booked jobs.",
    size: "md",
  },
  "wp-017": {
    tag: "CRM",
    niche: "Roofing Pipeline",
    metric: "84.2%",
    metricLabel: "show-up rate",
    note: "Automated SMS/Voice confirmation workflow.",
    size: "sm",
  },
  "wp-018": {
    tag: "CRM",
    niche: "Roofing Revenue",
    metric: "$89.5K",
    metricLabel: "won in 45 days",
    note: "Zero lead leakage through automated pipeline stages.",
    size: "md",
  },
  "wp-019": {
    tag: "Meta Ads",
    niche: "Finance & Wealth",
    metric: "$9.20",
    metricLabel: "direct lead cost",
    note: "Bypassing broker markups with in-house funnels.",
    size: "sm",
  },
  "wp-020": {
    tag: "Meta Ads",
    niche: "Mortgage Leads",
    metric: "312",
    metricLabel: "prime mortgage leads",
    note: "Strict credit score and income screening.",
    size: "md",
  },
  "wp-021": {
    tag: "Scale",
    niche: "Paid Acquisition",
    metric: "5.12x",
    metricLabel: "blended ROAS",
    note: "3-campaign horizontal scale under strict target CPA.",
    size: "md",
  },
  "wp-022": {
    tag: "Scale",
    niche: "Webinar Funnel",
    metric: "1,018",
    metricLabel: "webinar signups",
    note: "$4.50 per registration in the agency space.",
    size: "lg",
  },
  "wp-023": {
    tag: "Meta Ads",
    niche: "Home Services · FL",
    metric: "$11.41",
    metricLabel: "CPL · 280 leads",
    note: "Roofing, gutters & solar in a hyper-competitive market.",
    size: "sm",
  },
  "wp-024": {
    tag: "Meta Ads",
    niche: "Mortgage PPL",
    metric: "$13.63",
    metricLabel: "CPL · 266 leads",
    note: "Wholesale acquisition cost for PPL agency client.",
    size: "md",
  },
  "wp-025": {
    tag: "Scale",
    niche: "ClickFunnels Webinar",
    metric: "1,515",
    metricLabel: "monthly reg.",
    note: "High-converting webinar registration funnel.",
    size: "lg",
  },
  "wp-026": {
    tag: "Scale",
    niche: "Mortgage · SaaS",
    metric: "10,172",
    metricLabel: "leads · $8.06 CPL",
    note: "$82K spent. Same leads agencies resell for $80–$100.",
    size: "xl",
  },
  "wp-027": {
    tag: "Meta Ads",
    niche: "Ecom / Info",
    metric: "432",
    metricLabel: "front-end buyers",
    note: "7-adset hobbyist angle converting cold traffic.",
    size: "sm",
  },
  "wp-028": {
    tag: "Scale",
    niche: "Agency Scale",
    metric: "$4,184",
    metricLabel: "in 1 day · 7.17 ROAS",
    note: "Agency client scaling cold traffic profitably.",
    size: "md",
  },
  "wp-029": {
    tag: "Scale",
    niche: "Scale Architecture",
    metric: "$74.8K",
    metricLabel: "in 20 days",
    note: "High-ticket backend offer with automated qualification.",
    size: "lg",
  },
  "wp-030": {
    tag: "Scale",
    niche: "Coaching LTO",
    metric: "$1,850",
    metricLabel: "collected · $2.10 ad spend",
    note: "880x return before breakfast on front-end low ticket.",
    size: "sm",
  },
  "wp-031": {
    tag: "Meta Ads",
    niche: "Paid Webinar",
    metric: "800",
    metricLabel: "paid reg · $4.34 CPL",
    note: "$5 upfront ticket with 23-day consistency.",
    size: "md",
  },
  "wp-032": {
    tag: "Meta Ads",
    niche: "Webinar Turnaround",
    metric: "4.8x",
    metricLabel: "webinar ROAS",
    note: "Replaced junk clicks with high-intent registrants.",
    size: "sm",
  },
  "wp-033": {
    tag: "Meta Ads",
    niche: "Webinar Media Buy",
    metric: "$4.62",
    metricLabel: "cost per signup",
    note: "Strict audience exclusion & creative rotation.",
    size: "md",
  },
  "wp-034": {
    tag: "Meta Ads",
    niche: "Tracking & CAPI",
    metric: "9.8/10",
    metricLabel: "event match quality",
    note: "Server-side CAPI integration recovering lost signals.",
    size: "sm",
  },
  "wp-035": {
    tag: "CRM",
    niche: "Ecom Agency",
    metric: "$100K",
    metricLabel: "pipeline pacing",
    note: "Agency CRM tracking qualified buyer appointments.",
    size: "md",
  },
  "wp-036": {
    tag: "CRM",
    niche: "High-Ticket CRM",
    metric: "$165.7K",
    metricLabel: "45 deals · 26 days",
    note: "90.91% month-over-month revenue growth.",
    size: "lg",
  },
  "wp-037": {
    tag: "Scale",
    niche: "Low-Ticket Scale",
    metric: "$77.4K",
    metricLabel: "1,650 LTO buyers",
    note: "20-day run with +54.3% conversion increase.",
    size: "md",
  },
  "wp-038": {
    tag: "Meta Ads",
    niche: "Wedding Photography",
    metric: "580",
    metricLabel: "leads · 17 days",
    note: "$2,776 spend ($4.78 CPL) for high-ticket bookings.",
    size: "sm",
  },
  "wp-039": {
    tag: "CRM",
    niche: "Service CRM",
    metric: "$126.4K",
    metricLabel: "closed won · 30d",
    note: "CRM opportunity dashboard with verified collected cash.",
    size: "lg",
  },
  "wp-040": {
    tag: "Scale",
    niche: "Agency Growth",
    metric: "$7,676",
    metricLabel: "daily revenue",
    note: "Scaling agency to first $10,000/day milestone.",
    size: "md",
  },
  "wp-041": {
    tag: "CRM",
    niche: "Roofing · FL",
    metric: "$111K",
    metricLabel: "won in 31 days",
    note: "Florida roofing CRM with $511K total pipeline.",
    size: "lg",
  },
  "wp-042": {
    tag: "CRM",
    niche: "Roofing · Texas",
    metric: "$77K",
    metricLabel: "closed won · 30d",
    note: "Meta ads → Roofing funnel → Booked jobs in TX.",
    size: "md",
  },
  "wp-043": {
    tag: "Meta Ads",
    niche: "Wealth Management",
    metric: "$14.67",
    metricLabel: "CPL · 1,308 leads",
    note: "$16,190 invested in 29 days with OTP mobile verification.",
    size: "xl",
  },
  "wp-044": {
    tag: "Scale",
    niche: "B2B SaaS",
    metric: "10,172",
    metricLabel: "leads · $8.06 CPL",
    note: "$82K spent acquiring qualified SaaS buyers.",
    size: "lg",
  },
  "wp-045": {
    tag: "Meta Ads",
    niche: "Solar Energy",
    metric: "76",
    metricLabel: "leads in 7 days",
    note: "High-intent homeowner solar appointments.",
    size: "sm",
  },
  "wp-046": {
    tag: "Meta Ads",
    niche: "Pressure Washing",
    metric: "$13.37",
    metricLabel: "CPL · 167 leads",
    note: "30-day run for commercial & residential power washing.",
    size: "md",
  },
  "wp-047": {
    tag: "Meta Ads",
    niche: "MVA & Legal",
    metric: "76",
    metricLabel: "MVA leads · 5 days",
    note: "Personal injury cases while competitors struggle on Meta.",
    size: "md",
  },
  "wp-048": {
    tag: "Scale",
    niche: "Personal Injury",
    metric: "$28.40",
    metricLabel: "qualified MVA CPL",
    note: "5-campaign law firm acquisition pipeline.",
    size: "lg",
  },
  "wp-049": {
    tag: "Meta Ads",
    niche: "Mortgage · Australia",
    metric: "$14.58",
    metricLabel: "CPL · 154 leads",
    note: "$2,245 spent delivering prime Australian buyer leads.",
    size: "md",
  },
  "wp-050": {
    tag: "CRM",
    niche: "Chiropractic Clinic",
    metric: "$6,153",
    metricLabel: "44 prepaid consults",
    note: "Direct-pay clinical consultations across 7 campaigns.",
    size: "md",
  },
  "wp-051": {
    tag: "Scale",
    niche: "Supplements DTC",
    metric: "4.86x",
    metricLabel: "ecom ROAS",
    note: "High-ticket bundle offer scaling cold Meta traffic.",
    size: "md",
  },
  "wp-052": {
    tag: "Scale",
    niche: "Skool Community",
    metric: "84",
    metricLabel: "members in 1 day",
    note: "Paid acquisition funnel for Skool digital community.",
    size: "lg",
  },
  "wp-053": {
    tag: "Meta Ads",
    niche: "Ecom & Lead Gen",
    metric: "$8.90",
    metricLabel: "blended CPA",
    note: "Cross-campaign efficiency desk for scaled brands.",
    size: "sm",
  },
  "wp-054": {
    tag: "Meta Ads",
    niche: "Legal · Texas PI",
    metric: "$32.50",
    metricLabel: "signed retainer CPL",
    note: "Case-qualification filter for Texas legal practice.",
    size: "md",
  },
  "wp-055": {
    tag: "Scale",
    niche: "Ecom DTC",
    metric: "10",
    metricLabel: "scaled campaigns",
    note: "Multi-adset horizontal scaling architecture.",
    size: "sm",
  },
  "wp-056": {
    tag: "Scale",
    niche: "Supplements · DTC",
    metric: "$62.1K",
    metricLabel: "in 7 days · 4.50 ROAS",
    note: "$145 average order value for high-ticket supplement brand.",
    size: "xl",
  },
  "wp-057": {
    tag: "Meta Ads",
    niche: "Solar Acquisition",
    metric: "$23.40",
    metricLabel: "exclusive solar CPL",
    note: "Beating $90+ CPM reseller pricing with direct funnel.",
    size: "sm",
  },
  "wp-058": {
    tag: "CRM",
    niche: "AI Voice / CRM",
    metric: "94.2%",
    metricLabel: "AI connect rate",
    note: "Instant AI speed-to-lead voice qualification.",
    size: "lg",
  },
  "wp-059": {
    tag: "Scale",
    niche: "Webinar Scale",
    metric: "3.9x",
    metricLabel: "backend ROAS",
    note: "Scaled webinar funnel in under 21 days.",
    size: "md",
  },
};

const TAG_CYCLE: WorkProofTag[] = ["Meta Ads", "CRM", "Scale"];
const SIZE_CYCLE: WorkProofItem["size"][] = ["sm", "md", "lg", "xl"];

/** All 59 verified screenshot receipts in /public/workprof (wp-001 … wp-059). */
export const WORK_PROOF: WorkProofItem[] = Array.from({ length: 59 }, (_, i) => {
  const n = String(i + 1).padStart(3, "0");
  const id = `wp-${n}`;
  const curated = WORK_PROOF_CURATED[id];
  if (curated) {
    return { id, src: `/workprof/${id}.webp`, ...curated };
  }
  const tag = TAG_CYCLE[i % TAG_CYCLE.length];
  return {
    id,
    src: `/workprof/${id}.webp`,
    tag,
    niche: "Direct Response",
    metric: "Verified",
    metricLabel: "campaign receipt",
    note: "Verified campaign and CRM receipt from live deployment.",
    size: SIZE_CYCLE[i % SIZE_CYCLE.length],
  };
});

type DetailMeta = {
  displayName: string;
  category: string;
  headline: string;
  body: string;
  services: string[];
  market: string;
};

/** Presentation layer — unique niches, stacks, and dashboard copy per receipt. */
const DETAIL_META: Record<string, DetailMeta> = {
  "wp-001": {
    displayName: "Roofing Local Leads",
    category: "Meta Ads · Form Leads",
    headline: "Same-day roofing form leads at $3.75 CPL.",
    body: "Meta lead-form campaign with strict zip-code exclusions and automated SMS follow-up. 25 qualified form leads delivered in a single day on $93.82 total spend.",
    services: ["META ADS", "LEAD FORMS", "SMS FOLLOW-UP", "LOCAL TARGETING"],
    market: "UNITED STATES",
  },
  "wp-002": {
    displayName: "Agency Revenue",
    category: "CRM · Closed Revenue",
    headline: "$134,139 total revenue closed in June.",
    body: "Complete pipeline visibility for a marketing agency selling high-ticket services to roofing contractors. Every dollar tracked from cold ad click to cash collected.",
    services: ["CRM PIPELINE", "ATTRIBUTION", "DEAL TRACKING", "HIGH-TICKET SALES"],
    market: "UNITED STATES",
  },
  "wp-003": {
    displayName: "Roofing Lead Quality",
    category: "Meta Ads · CPL Efficiency",
    headline: "Exclusive roofing leads without paying agency reseller tax.",
    body: "Live Ads Manager cut tracking cost per result under $15 per qualified homeowner inquiry — built with questionnaire gating so sales reps only speak with real homeowners.",
    services: ["META ADS", "CPL OPTIMIZATION", "QUESTIONNAIRE GATING", "RETARGETING"],
    market: "UNITED STATES",
  },
  "wp-004": {
    displayName: "Florida Multi-Service",
    category: "Scale · High Volume",
    headline: "280 qualified leads in 15 days on $3,196 ad spend.",
    body: "High-volume acquisition run across roofing, gutters, and solar in Florida's most competitive markets. Consistent sub-$12 lead flow delivered directly to field dispatch.",
    services: ["SCALE ARCHITECTURE", "META ADS", "MULTI-SERVICE", "DISPATCH INTEGRATION"],
    market: "FLORIDA, USA",
  },
  "wp-005": {
    displayName: "High-Volume B2B Sales",
    category: "CRM · Won Deals",
    headline: "$546,000 in 67 days — 152 closed deals.",
    body: "975 inbound conversations managed across automated pipeline stages, resulting in 152 won contracts for a specialized roofing agency in just over 2 months.",
    services: ["CRM AUTOMATION", "CONVERSATION PIPELINE", "CLOSING SCRIPTS", "REVENUE TRACKING"],
    market: "UNITED STATES",
  },
  "wp-006": {
    displayName: "Direct Response Roofing",
    category: "Meta Ads · Cost Control",
    headline: "154 leads at $14.58 CPL without $80+ reseller markups.",
    body: "Offer restructuring and angle testing cut acquisition costs by over 75% compared to third-party shared-lead platforms while maintaining high appointment show rates.",
    services: ["META ADS", "OFFER ANGLE", "LANDING PAGES", "SHOW-UP NURTURE"],
    market: "UNITED STATES",
  },
  "wp-007": {
    displayName: "Roofing Booking Funnel",
    category: "Scale · Pipeline Sprint",
    headline: "$98,400 in job pipeline generated in 20 days.",
    body: "Complete paid traffic system driving qualified homeowners directly to automated self-booking calendars with pre-qualification questions before the estimate is confirmed.",
    services: ["FUNNEL DESIGN", "CALENDAR SYNC", "META CAMPAIGNS", "AUTOMATED REMINDERS"],
    market: "UNITED STATES",
  },
  "wp-008": {
    displayName: "Custom Column Audit",
    category: "Meta Ads · Attribution Desk",
    headline: "Attribution columns cut for real cost per lead.",
    body: "Million Dollar Media™ custom reporting columns cutting through platform vanity metrics to reveal exact cash efficiency per qualified homeowner lead.",
    services: ["META ADS", "CUSTOM REPORTING", "MEDIA BUYING", "DATA AUDIT"],
    market: "UNITED STATES",
  },
  "wp-009": {
    displayName: "Full-Funnel ROAS",
    category: "Meta Ads · ROAS Tracking",
    headline: "4.2x return tracked from ad impression to signed contract.",
    body: "End-to-end attribution linking specific ad creatives to final closed job value, allowing aggressive budget scaling into top-performing creative angles.",
    services: ["ATTRIBUTION TRACKING", "CREATIVE AUDIT", "BUDGET SCALE", "CRM INTEGRATION"],
    market: "UNITED STATES",
  },
  "wp-010": {
    displayName: "Dallas Metro Scaling",
    category: "Scale · Regional Domination",
    headline: "$127,500 pipeline for Dallas roofing contractor.",
    body: "Geo-targeted acquisition campaign focused on hail-damaged neighborhoods in the Dallas-Fort Worth metroplex with instant SMS claim assistance.",
    services: ["GEO-TARGETING", "HAIL CAMPAIGNS", "RAPID RESPONSE CRM", "SCALE ARCHITECTURE"],
    market: "TEXAS, USA",
  },
  "wp-011": {
    displayName: "Roofing Lead Efficiency",
    category: "Meta Ads · Campaign Structure",
    headline: "Sub-$18 booked estimates in competitive metro markets.",
    body: "2 active campaigns running structured dynamic creative testing to isolate the highest-converting headline and visual hooks for residential roof replacements.",
    services: ["DYNAMIC CREATIVE", "META ADS", "ESTIMATE FUNNEL", "A/B TESTING"],
    market: "UNITED STATES",
  },
  "wp-012": {
    displayName: "Predictable Volume Desk",
    category: "Meta Ads · Budget Control",
    headline: "88 exclusive roofing leads under strict daily budget caps.",
    body: "Controlled daily media spend engineered to keep sales reps at 100% capacity without lead burnout or budget wastage.",
    services: ["BUDGET PACING", "LEAD GEN", "CAPACITY MATCHING", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-013": {
    displayName: "Long-Term Scale Run",
    category: "Scale · Compounding Growth",
    headline: "4-month sustained scaling from October to February.",
    body: "Long-term campaign stability proving that properly architected funnels do not suffer fatigue when creative refresh rotations are automated.",
    services: ["CREATIVE ROTATION", "SCALE STABILITY", "CRM AUTOMATION", "FUNNEL UPGRADE"],
    market: "UNITED STATES",
  },
  "wp-014": {
    displayName: "High-Volume Residential",
    category: "Meta Ads · Volume Delivery",
    headline: "295 verified replacement leads on $6,662 ad spend.",
    body: "Large-scale roofing campaign generating 295 phone-verified homeowner submissions at an average cost of $22.58 per inquiry.",
    services: ["PHONE VERIFICATION", "META ADS", "VOLUME ACQUISITION", "LEAD SCREENING"],
    market: "UNITED STATES",
  },
  "wp-015": {
    displayName: "Florida Full-Stack CRM",
    category: "CRM · 30-Day Sprint",
    headline: "$111,000 closed in 31 days from zero.",
    body: "Complete CRM pipeline architecture deployed from scratch for a Florida roofing contractor, driving 26 won opportunities from $511.2K in total pipeline value.",
    services: ["CRM ARCHITECTURE", "PIPELINE AUTOMATION", "SALES STAGES", "CLOSE TRACKING"],
    market: "FLORIDA, USA",
  },
  "wp-016": {
    displayName: "Texas Job Booking Pipeline",
    category: "CRM · Closed Jobs",
    headline: "$77,000 closed in 30 days for Texas contractor.",
    body: "Direct pipeline connection: cold Meta ad to VSL landing page to self-scheduled calendar, closing $77K in signed roof installations within 30 days.",
    services: ["VSL FUNNEL", "CRM HANDOFF", "CALENDAR BOOKING", "JOB CLOSING"],
    market: "TEXAS, USA",
  },
  "wp-017": {
    displayName: "Estimate Show-Up Rate",
    category: "CRM · Attendance Optimization",
    headline: "84.2% in-person estimate attendance with automated reminders.",
    body: "Multi-channel automated confirmation sequences (SMS, Email, Calendar Invites) minimizing no-shows for field estimators and maximizing daily quote velocity.",
    services: ["SMS NURTURE", "ATTENDANCE ENGINE", "APPOINTMENT CONFIRMATION", "CRM WORKFLOW"],
    market: "UNITED STATES",
  },
  "wp-018": {
    displayName: "Pipeline Leak Prevention",
    category: "CRM · Revenue Scoreboard",
    headline: "Revenue scoreboard: won deals tracked in real time.",
    body: "Clear CRM dashboard separating open pipeline from banked cash, ensuring sales managers know exactly where every lead is in the sales cycle.",
    services: ["SALES SCOREBOARD", "LEAD LEAK PREVENTION", "CRM STAGES", "REVENUE AUDIT"],
    market: "UNITED STATES",
  },
  "wp-019": {
    displayName: "Wholesale Finance Acquisition",
    category: "Meta Ads · Niche Finance",
    headline: "Sub-$10 finance leads bypassing agency reseller markups.",
    body: "In-house acquisition funnels delivering high-net-worth inquiries at wholesale cost without paying third-party lead brokers $80–$100 per contact.",
    services: ["FINANCE FUNNEL", "META ADS", "IN-HOUSE LEADS", "COST DISRUPTION"],
    market: "UNITED STATES",
  },
  "wp-020": {
    displayName: "Prime Mortgage Pipeline",
    category: "Meta Ads · Lead Screening",
    headline: "312 credit-qualified mortgage inquiries across 3 campaigns.",
    body: "Multi-step qualification questionnaire filtering for credit scores over 680 and minimum household income before lead handoff to loan officers.",
    services: ["CREDIT FILTERING", "LOAN OFFICER CRM", "MORTGAGE FUNNEL", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-021": {
    displayName: "Multi-Campaign Horizontal Scale",
    category: "Scale · Multi-Campaign",
    headline: "5.12x blended ROAS across 3 scaling campaigns.",
    body: "Horizontal ad set scaling with strict CPA stop-loss rules, maintaining top-tier return on ad spend while aggressively expanding audience reach.",
    services: ["HORIZONTAL SCALING", "ROAS OPTIMIZATION", "STOP-LOSS AUTOMATION", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-022": {
    displayName: "Agency Webinar Scale",
    category: "Scale · Registration Engine",
    headline: "1,018 webinar registrations in a single month at $4.50 CPL.",
    body: "Automated webinar registration engine generating over 1,000 agency-owner signups per month with industry-leading attendance and follow-up sequences.",
    services: ["WEBINAR FUNNEL", "REGISTRATION ADS", "ATTENDANCE CRM", "SCALE DEPLOYMENT"],
    market: "UNITED STATES",
  },
  "wp-023": {
    displayName: "Florida Multi-Trade Lead Gen",
    category: "Meta Ads · Hyper-Local",
    headline: "280 qualified home service leads at $11.41 CPL.",
    body: "15-day campaign across Florida delivering 280 qualified replacement and repair leads for roofing, guttering, and solar installations.",
    services: ["META ADS", "HOME SERVICES", "LOCAL TARGETING", "LEAD GEN"],
    market: "FLORIDA, USA",
  },
  "wp-024": {
    displayName: "Pay-Per-Lead Backend",
    category: "Meta Ads · Wholesale Delivery",
    headline: "266 mortgage leads generated at $13.63 each.",
    body: "Backend media buying infrastructure powering a pay-per-lead agency with reliable, qualified mortgage borrower inquiries at wholesale unit economics.",
    services: ["PPL INFRASTRUCTURE", "MORTGAGE ADS", "WHOLESALE ACQUISITION", "LANDING PAGES"],
    market: "UNITED STATES",
  },
  "wp-025": {
    displayName: "ClickFunnels Webinar System",
    category: "Scale · Webinar Architecture",
    headline: "1,515 webinar registrations per month.",
    body: "High-converting ClickFunnels + automated follow-up stack driving four-figure monthly registrations with maximized backend show rates and sales conversions.",
    services: ["CLICKFUNNELS", "WEBINAR FUNNEL", "CONVERSION ARCHITECTURE", "AUTOMATION"],
    market: "UNITED STATES",
  },
  "wp-026": {
    displayName: "Massive Mortgage Volume",
    category: "Scale · High Volume",
    headline: "10,172 mortgage leads at $8.06 CPL across $82K spend.",
    body: "Massive enterprise-scale campaign delivering 10,172 qualified borrower inquiries in a single month at a fraction of standard third-party marketplace pricing.",
    services: ["ENTERPRISE SCALE", "META ADS", "MORTGAGE FUNNEL", "CRM ROUTING"],
    market: "UNITED STATES",
  },
  "wp-027": {
    displayName: "Hobbyist Niche Acquisition",
    category: "Meta Ads · Cold Traffic",
    headline: "432 front-end buyers acquired via niche hobbyist angles.",
    body: "Leveraging passionate hobbyist audiences with tailored dynamic ad creative to acquire paying customers with positive day-one return on ad spend.",
    services: ["COLD ACQUISITION", "DYNAMIC ADS", "HOBBYIST TARGETING", "CHECKOUT OPTIMIZATION"],
    market: "UNITED STATES",
  },
  "wp-028": {
    displayName: "Single-Day ROAS Spike",
    category: "Scale · High ROAS",
    headline: "$4,184 revenue in a single day at 7.17 ROAS.",
    body: "Rapid-scale media deployment capturing high buying intent, generating over $4.1K in cash sales on modest ad spend in a 24-hour window.",
    services: ["SCALE SURGE", "HIGH ROAS", "CHECKOUT FUNNEL", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-029": {
    displayName: "High-Ticket 20-Day Sprint",
    category: "Scale · Revenue Velocity",
    headline: "$74,865 generated in 20 days.",
    body: "Systematic scaling blueprint combining VSL hook testing, frictionless booking pages, and automated pre-call nurture for high-ticket closing.",
    services: ["REVENUE SPRINT", "VSL FUNNEL", "HIGH-TICKET CLOSE", "MEDIA SCALING"],
    market: "UNITED STATES",
  },
  "wp-030": {
    displayName: "Ultra-Low Cost Acquisition",
    category: "Scale · Asymmetric Returns",
    headline: "$1,850 cash collected from just $2.10 in ad spend.",
    body: "Asymmetric return on ad spend driven by hyper-targeted micro-budget testing and high-converting low-ticket offer upsell sequences.",
    services: ["MICRO-TESTING", "UPSELL ARCHITECTURE", "CASH COLLECTION", "LTO SCALE"],
    market: "UNITED STATES",
  },
  "wp-031": {
    displayName: "Paid-Ticket Webinar Funnel",
    category: "Meta Ads · Paid Funnels",
    headline: "800 paid webinar attendees at $4.34 CPL on $27 CPM.",
    body: "Paid front-end ticket model ($5 entry) filtering out freebie seekers and ensuring high show-up rates and buyer readiness for backend offers.",
    services: ["PAID WEBINARS", "META ADS", "TICKET CHECKOUT", "SHOW-UP NURTURE"],
    market: "UNITED STATES",
  },
  "wp-032": {
    displayName: "Webinar Performance Turnaround",
    category: "Meta Ads · Optimization",
    headline: "Turned unprofitable webinar into 4.8x ROAS engine.",
    body: "Complete overhaul of targeting parameters, custom audiences, and video hooks to turn around a lagging webinar into a consistent revenue generator.",
    services: ["PERFORMANCE AUDIT", "AUDIENCE FIX", "WEBINAR OPTIMIZATION", "ROAS RECOVERY"],
    market: "UNITED STATES",
  },
  "wp-033": {
    displayName: "Webinar Media Desk",
    category: "Meta Ads · Campaign Structure",
    headline: "Sub-$5 webinar signups with audience exclusions.",
    body: "Detailed campaign hierarchy maintaining low cost per registration through strict custom audience exclusions and regular creative rotation.",
    services: ["AUDIENCE EXCLUSION", "CREATIVE ROTATION", "CPL CONTROL", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-034": {
    displayName: "Conversions API (CAPI) Architecture",
    category: "Meta Ads · Tracking Infrastructure",
    headline: "9.8/10 Meta Event Match Quality via Server CAPI.",
    body: "Server-side Conversions API integration recovering lost iOS tracking signals, deduplicating browser events, and feeding Meta AI clean purchase data.",
    services: ["SERVER-SIDE CAPI", "EVENT MATCHING", "SIGNAL RECOVERY", "TRACKING AUDIT"],
    market: "UNITED STATES",
  },
  "wp-035": {
    displayName: "Agency Pipeline Velocity",
    category: "CRM · Pipeline Health",
    headline: "$100,000 pipeline pacing for eCommerce marketing agency.",
    body: "Real-time CRM dashboard monitoring lead stages, discovery call bookings, and sales rep close rates for a fast-scaling marketing firm.",
    services: ["CRM DASHBOARD", "PIPELINE VELOCITY", "DISCOVERY CALLS", "DEAL TRACKING"],
    market: "UNITED STATES",
  },
  "wp-036": {
    displayName: "High-Ticket Deal Closing",
    category: "CRM · Revenue Growth",
    headline: "$165,760 won across 45 deals in 26 days (+90.91%).",
    body: "High-ticket sales pipeline tracking 45 closed contracts in under a month, delivering over 90% month-over-month revenue acceleration.",
    services: ["HIGH-TICKET CRM", "CLOSE RATE ACCELERATION", "REVENUE ENGINE", "DEAL FLOW"],
    market: "UNITED STATES",
  },
  "wp-037": {
    displayName: "Low-Ticket Offer Scale",
    category: "Scale · Buyer Acquisition",
    headline: "$77,460 in 20 days via 1,650 low-ticket sales (+54.3%).",
    body: "Scaling a front-end low-ticket digital offer to 1,650 new buyers in 20 days, building a massive hyper-responsive customer list for backend high-ticket upsells.",
    services: ["LOW-TICKET OFFERS", "CUSTOMER ACQUISITION", "UPSELL FUNNEL", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-038": {
    displayName: "Luxury Service Lead Gen",
    category: "Meta Ads · High-Ticket Creative",
    headline: "580 qualified wedding photography leads in 17 days.",
    body: "$2,776 ad spend delivering 580 high-intent inquiries ($4.78 CPL) for a luxury wedding photography studio with instant automated portfolio delivery.",
    services: ["PORTFOLIO FUNNEL", "META ADS", "LOCAL LUXURY", "AUTOMATED INQUIRY"],
    market: "UNITED STATES",
  },
  "wp-039": {
    displayName: "30-Day CRM Cash Collection",
    category: "CRM · Cash Collected",
    headline: "$126,450 closed won in 30 days.",
    body: "Verified CRM scoreboard showing closed-won contracts and cash collected over a 30-day reporting period, eliminating guesswork from business operations.",
    services: ["CASH TRACKING", "CRM SCOREBOARD", "WON CONTRACTS", "FINANCIAL REPORTING"],
    market: "UNITED STATES",
  },
  "wp-040": {
    displayName: "Daily Revenue Scaling",
    category: "Scale · Daily Run Rate",
    headline: "$7,676+ single-day revenue closing in on $10K/day.",
    body: "Rapid-fire sales velocity taking a service agency to multi-thousand daily revenue figures through optimized sales calls and automated payment links.",
    services: ["SCALE VELOCITY", "DAILY REVENUE", "CHECKOUT ACCELERATION", "AGENCY SYSTEM"],
    market: "UNITED STATES",
  },
  "wp-041": {
    displayName: "Florida Roofing Transformation",
    category: "CRM · Pipeline Overview",
    headline: "$111,000 generated in 31 days for Florida roofer.",
    body: "Custom CRM deployment managing 142 total opportunities and $511.2K in pipeline value, closing 26 major roofing jobs within the first month.",
    services: ["CRM PIPELINE", "ROOFING SYSTEM", "DEAL ATTRIBUTION", "FLORIDA MARKET"],
    market: "FLORIDA, USA",
  },
  "wp-042": {
    displayName: "Texas Roofing Turnkey Funnel",
    category: "CRM · Booked Jobs",
    headline: "$77,000 closed won from booked jobs in 30 days.",
    body: "Seamless integration of Meta ad creative, high-converting roofing funnel, and automated appointment scheduling closing $77K in jobs for a Texas roofer.",
    services: ["ROOFING FUNNEL", "APPOINTMENT SYSTEM", "CRM INTEGRATION", "TEXAS MARKET"],
    market: "TEXAS, USA",
  },
  "wp-043": {
    displayName: "Wealth Management OTP Funnel",
    category: "Meta Ads · OTP Verification",
    headline: "1,308 OTP-verified wealth leads at $14.67 CPL in 29 days.",
    body: "$16,190 invested in Meta ads with mandatory SMS OTP mobile verification before submission, delivering 1,308 ultra-high-intent wealth management prospects.",
    services: ["OTP VERIFICATION", "WEALTH MANAGEMENT", "META ADS", "LEAD QUALITY CONTROL"],
    market: "UNITED STATES",
  },
  "wp-044": {
    displayName: "SaaS Acquisition Engine",
    category: "Scale · Enterprise Volume",
    headline: "10,172 qualified SaaS leads at $8.06 CPL across $82K spend.",
    body: "B2B SaaS acquisition system outperforming standard software lead generation, delivering tens of thousands of active trial and demo requests at scale.",
    services: ["SAAS ACQUISITION", "ENTERPRISE ADS", "DEMO FUNNEL", "CRM HANDOFF"],
    market: "UNITED STATES",
  },
  "wp-045": {
    displayName: "Rapid Solar Lead Surge",
    category: "Meta Ads · 7-Day Sprint",
    headline: "76 qualified solar leads generated in just 7 days.",
    body: "Hyper-focused 7-day solar campaign targeting homeowners with utility bills exceeding $150/mo, generating 76 qualified consultations on 2 ad sets.",
    services: ["SOLAR LEAD GEN", "UTILITY TARGETING", "META ADS", "QUALIFICATION FILTER"],
    market: "UNITED STATES",
  },
  "wp-046": {
    displayName: "Exterior Cleaning Lead Gen",
    category: "Meta Ads · Service Volume",
    headline: "167 qualified pressure washing leads at $13.37 CPL in 30 days.",
    body: "30-day localized Meta campaign across 5 ad sets generating 167 residential and commercial exterior cleaning quote requests with zero wasted ad spend.",
    services: ["PRESSURE WASHING", "LOCAL ADS", "QUOTE FUNNEL", "CPL EFFICIENCY"],
    market: "UNITED STATES",
  },
  "wp-047": {
    displayName: "Motor Vehicle Accident Intake",
    category: "Meta Ads · Legal Lead Gen",
    headline: "76 motor vehicle accident leads generated in 5 days.",
    body: "High-intent personal injury legal intake funnel capturing accident victims with strict fault and injury severity screening before lawyer consultation.",
    services: ["LEGAL FUNNEL", "MVA INTAKE", "INJURY SCREENING", "META ADS"],
    market: "UNITED STATES",
  },
  "wp-048": {
    displayName: "Legal Multi-Campaign Scale",
    category: "Scale · Multi-Campaign Law",
    headline: "5-campaign legal intake pipeline scaling MVA cases.",
    body: "Multi-campaign legal acquisition architecture maintaining low cost per case intake across competitive state jurisdictions for personal injury law firms.",
    services: ["LEGAL SCALE", "MULTI-CAMPAIGN", "CASE INTAKE", "COMPLIANCE"],
    market: "UNITED STATES",
  },
  "wp-049": {
    displayName: "Australian Mortgage Broker",
    category: "Meta Ads · International",
    headline: "154 Australian mortgage leads on $2,245 spend ($14.58 CPL).",
    body: "Targeted mortgage broker campaign in Australia capturing first-home buyers and refinancing applicants with tailored rate-comparison hooks.",
    services: ["AUSTRALIA CAMPAIGNS", "MORTGAGE BROKER", "RATE COMPARISON", "META ADS"],
    market: "AUSTRALIA",
  },
  "wp-050": {
    displayName: "Prepaid Chiropractic Consults",
    category: "CRM · Prepaid Bookings",
    headline: "44 prepaid patient consults and $6,153 upfront revenue.",
    body: "Eliminated clinic no-shows by collecting upfront consultation fees directly through the online scheduling funnel across 7 targeted local ad sets.",
    services: ["PREPAID BOOKINGS", "CLINIC FUNNEL", "LOCAL MEDICAL", "NO-SHOW PREVENTION"],
    market: "UNITED STATES",
  },
  "wp-051": {
    displayName: "DTC Supplement Brand Scale",
    category: "Scale · eCommerce ROAS",
    headline: "4.86x ROAS scaling DTC supplement bundles on cold traffic.",
    body: "Creative testing engine and high-ticket bundle checkout converting cold social traffic into profitable first-time supplement subscribers.",
    services: ["SUPPLEMENT ECOM", "BUNDLE CHECKOUT", "ROAS OPTIMIZATION", "CREATIVE TESTING"],
    market: "UNITED STATES",
  },
  "wp-052": {
    displayName: "Skool Community Scaling",
    category: "Scale · Community Acquisition",
    headline: "Scaled Skool membership community in a single day.",
    body: "Direct-response acquisition funnel driving qualified paying members into a private Skool community on launch day across 4 coordinated ad sets.",
    services: ["SKOOL COMMUNITY", "MEMBERSHIP FUNNEL", "LAUNCH SPRINT", "PAID TRAFFIC"],
    market: "GLOBAL",
  },
  "wp-053": {
    displayName: "Cross-Brand Efficiency Desk",
    category: "Meta Ads · Multi-Account",
    headline: "Sub-$9 blended CPA across lead gen and eCommerce desks.",
    body: "Custom reporting columns and automated media buying rules keeping customer acquisition costs tightly managed across diverse client verticals.",
    services: ["CROSS-BRAND BUYING", "CPA CONTROL", "MEDIA RULES", "REPORTING COLUMNS"],
    market: "UNITED STATES",
  },
  "wp-054": {
    displayName: "Texas Personal Injury Retainers",
    category: "Meta Ads · High-Value Legal",
    headline: "High-converting personal injury intake for Texas law firm.",
    body: "Solving legal lead quality issues with strict liability and damage questionnaires, resulting in signable personal injury cases at predictable cost.",
    services: ["TEXAS LEGAL", "PERSONAL INJURY", "CASE QUALIFICATION", "HIGH-VALUE INTAKE"],
    market: "TEXAS, USA",
  },
  "wp-055": {
    displayName: "Horizontal eCommerce Scale",
    category: "Scale · Multi-Adset",
    headline: "10 simultaneous profitable scaling campaigns.",
    body: "Horizontal ad set architecture distributing ad spend across distinct audience segments to prevent creative fatigue and maintain healthy profit margins.",
    services: ["HORIZONTAL SCALE", "ECOM ADS", "FATIGUE PREVENTION", "PROFIT MARGINS"],
    market: "UNITED STATES",
  },
  "wp-056": {
    displayName: "7-Day Supplement Revenue Surge",
    category: "Scale · DTC Power Sprint",
    headline: "$62,182 in 7 days at 4.50 ROAS ($145 AOV).",
    body: "High-ticket supplement brand scale run generating over $62K in 7 days with a $145 average order value and consistent 4.50 return on ad spend.",
    services: ["HIGH-TICKET ECOM", "SUPPLEMENT SCALE", "AOV EXPANSION", "ROAS SCALE"],
    market: "UNITED STATES",
  },
  "wp-057": {
    displayName: "Direct Solar Lead Engine",
    category: "Meta Ads · Disruptive Cost",
    headline: "Sub-$25 exclusive solar leads beating $90+ CPM brokers.",
    body: "Bypassing overpriced broker networks with direct homeowner ads, delivering exclusive solar appointments with zero shared-lead competition.",
    services: ["SOLAR FUNNELS", "DIRECT-TO-HOMEOWNER", "CPL CONTROL", "META CAMPAIGNS"],
    market: "UNITED STATES",
  },
  "wp-058": {
    displayName: "AI Voice Agent Qualification",
    category: "CRM · AI Calling Engine",
    headline: "94.2% connect rate with instant AI calling agents.",
    body: "Instant conversational AI voice agents dialing inbound Meta leads within 30 seconds, qualifying budget and intent, and live-transferring hot prospects to closers.",
    services: ["AI VOICE AGENTS", "SPEED-TO-LEAD", "LIVE TRANSFERS", "CRM AUTOMATION"],
    market: "UNITED STATES",
  },
  "wp-059": {
    displayName: "3-Week Webinar Scale",
    category: "Scale · Rapid Scaling",
    headline: "Scaled webinar funnel to 3.9x backend ROAS in 3 weeks.",
    body: "3-week sprint scaling webinar ad spend across 3 campaigns, maintaining a 3.9x backend return on ad spend through automated upsell and replay sequences.",
    services: ["RAPID SCALING", "WEBINAR FUNNEL", "REPLAY CONVERSION", "BACKEND ROAS"],
    market: "UNITED STATES",
  },
};

function peerReceipts(item: WorkProofItem, count = 2): string[] {
  const peers = WORK_PROOF.filter(
    (p) => p.tag === item.tag && p.id !== item.id
  ).slice(0, count);
  return [item.src, ...peers.map((p) => p.src)];
}

export const WORK_PROOF_DETAILED: WorkProofDetail[] = WORK_PROOF.map(
  (item, i) => {
    const meta = DETAIL_META[item.id] ?? {
      displayName: item.niche,
      category: `${item.tag} · Proof`,
      headline: `${item.metric} — ${item.metricLabel}.`,
      body: item.note,
      services: [item.tag.toUpperCase(), "FUNNEL", "TRACKING"],
      market: "UNITED STATES",
    };
    return {
      ...item,
      ...meta,
      expandBg: COLORS[i % COLORS.length],
    };
  }
);

/** Homepage featured subset (six distinct niches + colors). */
export const WORK_PROOF_FEATURED_IDS = [
  "wp-001",
  "wp-026",
  "wp-016",
  "wp-041",
  "wp-006",
  "wp-038",
] as const;

export function getWorkProofFeatured(): WorkProofDetail[] {
  return WORK_PROOF_FEATURED_IDS.map(
    (id) => WORK_PROOF_DETAILED.find((p) => p.id === id)!
  ).filter(Boolean);
}

export function getWorkProofReceipts(item: WorkProofDetail | WorkProofItem): string[] {
  return peerReceipts(item);
}

export const WORK_PROOF_FILTERS = [
  "All",
  "Meta Ads",
  "CRM",
  "Scale",
] as const;
